name: isolate_transformer
repository: https://github.com/AoEiuV020/isolate_transformer

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test