name: isolate_transformer
repository: https://github.com/AoEiuV020/isolate_transformer

packages:
  - apps/**
  - packages/**

scripts:
  worker2js:
    exec: cd web && dart compile js findPrimeNumbersTransform.dart -o findPrimeNumbersTransform.js -O4
    packageFilters:
      scope: 'example'

  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  doc:
    exec: dart doc .
    packageFilters:
      ignore: '*example*'
  analyze:
    exec: dart analyze .
  test:
    run: flutter test --no-pub --coverage
    exec:
      concurrency: 1
    failFast: true
    packageFilters:
      flutter: true
      dirExists: test