name: example
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  file_picker: ^8.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isolate_transformer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  js: ^0.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
