name: isolate_transformer
description: Cross-platform asynchronous thread invocation of Stream transformation methods.
version: 1.1.0
repository: https://github.com/AoEiuV020/isolate_transformer

environment:
  sdk: ^3.3.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
