# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag-pattern on pub.dev: 'v{{version}}'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    name: publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: bluefireteam/melos-action@v3
        with:
          publish: true
